### PR TITLE
Add yuml2svg as dependency

### LINKED ISSUE #23: Problem with Notes
There seems to be a problem with the 2.10.0 package, diagrams with notes aren't displayed correctly. Could this be related to the viz.js 1.7.1 upgrade? In my workspace, using 1.3.0, everything works fine.

### LINKED ISSUE #28: Chinese support before, now does not support Chinese?
Chinese is no longer supported after the automatic upgrade plug-in, but also plans to support Chinese?

### PR DESCRIPTION
**Pull request by aduh95**
This PR includes the work I have made the past week, and replaces #37.

* Update viz.js to v2 (Fixes #28) (Graphviz 2.40)
* Replace record shapes with rectangles (Fixes #23)
* Because viz.js v2 uses WebAssembly/asm.js build of Graphviz, the API is promisified. Unfortunatly `markdown-it` [doesn't deal well with asynchronous rendering](https://github.com/markdown-it/markdown-it/blob/master/docs/development.md#faq). Please review the workaround I have made to see if it can be improved.

I would suggest to wait for `viz.js` to release the final v2 version before merging this PR. In the mean time, reviews and improvement suggestions on [`yuml2svg`](https://github.com/aduh95/yuml2svg) are more than welcome.

### CODE REVIEW

**Comment by aduh95** [comment]
> In best case I would have to create my own npm.

I think I can hand you over the npm package `yuml2svg` if you're interested.

I get your point about the asynchronous problem, and for the markdown plugin, viz.js 1.8 makes more sense indeed.

**Comment by jaime-olivares** [comment]
I am checking there is not a 'yuml' npm package. So maybe it would be better to take it.
You can put a deprecation message in your yuml package pointing to mine, and I will keep mine updated.

**Comment by aduh95** [comment]
I am thinking of keeping my package around for people who prefer working with promises, at least as long you are not upgrading to viz.js v2... I guess it will depend on how much time I will have to spend for that!

Maybe I should reopen #37 and close this one, as it implements a full synchronous API, we'll just have to adapt the name of the dependency to whatever you choose.

**Comment by aduh95** [comment]
@jaime-olivares An idea just crossed my mind: what about making a `yuml2dot` package that could be processed with whatever version on Graphviz / viz.js anyone wants? I think that would address the PDF export request feature since Graphviz has an option to output a PDF. I would let the Sequence diagram behind though...

**Comment by jaime-olivares** [comment]
As you say, that wouldn't work for sequence and probably more incoming diagram types. making the graphviz version configurable will add unnecessary complexity. If some version works for all use cases, there is no need to do that.

**Comment by jaime-olivares** [comment]
Already working on the npm package: https://github.com/jaime-olivares/yuml

**Pull request closed without merging**
